### ISSUE TITLE
How to set background color of custom badge? 

### ISSUE THREAD

**Issue by snaeil** [six-two/mkdocs-badges#3]
I wanted to try out custom badges and tried to set a different background color.
I failed and don't know why.

My documentation contains:

```markdown
|Styled differently|by custom HTML classes|class:myclass|
```

My `docs/overrides/extra.css` contains

```css
.myclass {
  background-color: #FF0000;
  color: black;
}
```

My `mkdocs.yml` contains the theme attribute `custom_dir: docs/overrides`.

But still my badge doesn't change:

![2022-10-22-143446_342x53_scrot](https://user-images.githubusercontent.com/52743746/197339073-8182e199-c177-4498-a150-ed73aca0ac4c.png)

What am I doing wrong?

**Comment by six-two** [comment]
Hi, I have added a page detailing how to customise the styles to the [documentation](https://mkdocs-badges.six-two.dev/styling/). If that does not work for you/ you find any errors, please let me know by commenting here :)

**Comment by snaeil** [comment]
This helped and is working, thanks a lot!

In my case the custom css was wrong.

It had to be

```css
.badge.myclass .title {
  background-color: #FF0000;
  color: black;
}
```
